apiVersion: v1
kind: Secret
metadata:
  name: swm-route-optimizer-secrets
  namespace: default
type: Opaque
stringData:
  SWM_API_BASE_URL: "#{SWM_API_BASE_URL}#"
  EXTERNAL_UPLOAD_URL: "#{EXTERNAL_UPLOAD_URL}#"
