apiVersion: v1
kind: Secret
metadata:
  name: swm-route-optimizer-secrets
  namespace: default
type: Opaque
stringData:
  SWM_API_BASE_URL: ""
  SWM_USERNAME: ""
  SWM_PASSWORD: ""
  SWM_TOKEN: ""
  API_KEY: ""
  EXTERNAL_UPLOAD_URL: ""
  PORT: "8081"
  DEBUG: "true"
