apiVersion: v1
kind: Secret
metadata:
  name: swm-route-optimizer-secrets
  namespace: default
type: Opaque
stringData:
  SWM_API_BASE_URL: "https://swm-main-service-wap-htangag4ghgsfeg4.centralindia-01.azurewebsites.net/"
  SWM_USERNAME: "swmsuperadmin"
  SWM_PASSWORD: "Admin@123"
  SWM_TOKEN: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYXZpZCIsInJvbGVzIjpbIlNVUEVSQURNSU4iXSwid2FyZHMiOlsiV2FyZCAyOCIsIldhcmQgMCIsIldhcmQgMSIsIldhcmQgMTAiLCJXYXJkIDExIiwiV2FyZCAxNSIsIldhcmQgMTQiLCJXYXJkIDEzIiwiV2FyZCAxMiIsIldhcmQgMTYiLCJXYXJkIDE3IiwiV2FyZCAxOCIsIldhcmQgMTkiLCJXYXJkIDIyIiwiV2FyZCAyMCIsIldhcmQgMiIsIldhcmQgMjEiLCJXYXJkIDIzIiwiV2FyZCAyNCIsIldhcmQgMjUiLCJXYXJkIDI2IiwiV2FyZCAzIiwiV2FyZCAyOSIsIldhcmQgMjciLCJXYXJkIDMwIiwiV2FyZCAzNCIsIldhcmQgMzEiLCJXYXJkIDM1IiwiV2FyZCAzMiIsIldhcmQgMzYiLCJXYXJkIDMzIiwiV2FyZCAzNyIsIldhcmQgNyIsIldhcmQgNjciLCJXYXJkIDgiLCJXYXJkIDkiLCJXYXJkIDY2IiwiV2FyZCA2NSIsIldhcmQgNjQiLCJXYXJkIDYzIiwiV2FyZCA2IiwiV2FyZCA1NiIsIldhcmQgNTMiLCJXYXJkIDU3IiwiV2FyZCA2MCIsIldhcmQgNTgiLCJXYXJkIDYxIiwiV2FyZCA1OSIsIldhcmQgNjIiLCJXYXJkIDU1IiwiV2FyZCA1MSIsIldhcmQgNDgiLCJXYXJkIDQ3IiwiV2FyZCA1MCIsIldhcmQgNTQiLCJXYXJkIDQ2IiwiV2FyZCA1IiwiV2FyZCA0MiIsIldhcmQgNDEiLCJXYXJkIDQ1IiwiV2FyZCA0OSIsIldhcmQgNTIiLCJXYXJkIDM4IiwiV2FyZCAzOSIsIldhcmQgNCIsIldhcmQgNDMiLCJXYXJkIDQwIiwiV2FyZCA0NCJdLCJpc3MiOiJzb2xpZC13YXN0ZS1tYW5hZ2VtZW50IiwiYXVkIjpbInN3bS11c2VycyJdLCJpYXQiOjE3NjU0NDk0OTIsImV4cCI6MTc2NTUzNTg5Mn0.xhupQtzR-d-EL4EPSt_YRU3fUaxAeg27HTwZeBNcEc3v6hxaBqUbwUZweKdxgJs-ckazAoQybXu9na5RK73RrA"
  API_KEY: "swm-2024-secure-key"
  EXTERNAL_UPLOAD_URL: "https://swm-main-service-wap-htangag4ghgsfeg4.centralindia-01.azurewebsites.net/api/vehicle-routes/upload-data"
  PORT: "8081"
  DEBUG: "true"
