apiVersion: v1
kind: Secret
metadata:
  name: swm-route-optimizer-secrets
  namespace: default
type: Opaque
stringData:
  SWM_API_BASE_URL: "#{SWM_API_BASE_URL}#"
  SWM_USERNAME: "#{SWM_USERNAME}#"
  SWM_PASSWORD: "#{SWM_PASSWORD}#"
  EXTERNAL_UPLOAD_URL: "#{EXTERNAL_UPLOAD_URL}#"
  DEBUG: "#{DEBUG}#"
