apiVersion: v1
kind: Service
metadata:
  name: swm-route-optimizer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: swm-route-optimizer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
