apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swm-agent-ingress
  namespace: swm-routing-agent
  annotations:
    kubernetes.azure.com/tls-cert-keyvault-uri: "https://allvy-core-infra-kv.vault.azure.net/certificates/swm-agent-cert"
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
        - routing.swm-agent.com
      secretName: keyvault-swm-agnet-ingress
  rules:
    - host: routing.swm-agent.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swm-routing-agent-service
                port:
                  number: 80