apiVersion: v1
kind: Service
metadata:
  name: swm-routing-agent-service
  namespace: swm-routing-agent
spec:
  selector:
    app: swm-routing-agent
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP